-- database/fix_orders_checkout_columns.sql
DELIMITER //
CREATE PROCEDURE FixOrdersColumns()
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders' AND COLUMN_NAME = 'recipient_name') THEN
        ALTER TABLE orders ADD COLUMN recipient_name VARCHAR(255) DEFAULT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders' AND COLUMN_NAME = 'recipient_phone') THEN
        ALTER TABLE orders ADD COLUMN recipient_phone VARCHAR(30) DEFAULT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders' AND COLUMN_NAME = 'recipient_email') THEN
        ALTER TABLE orders ADD COLUMN recipient_email VARCHAR(255) DEFAULT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders' AND COLUMN_NAME = 'payment_method') THEN
        ALTER TABLE orders ADD COLUMN payment_method VARCHAR(50) DEFAULT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders' AND COLUMN_NAME = 'notes') THEN
        ALTER TABLE orders ADD COLUMN notes TEXT DEFAULT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders' AND COLUMN_NAME = 'cccd') THEN
        ALTER TABLE orders ADD COLUMN cccd VARCHAR(20) DEFAULT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders' AND COLUMN_NAME = 'store_id') THEN
        ALTER TABLE orders ADD COLUMN store_id INT DEFAULT NULL;
    END IF;
END //
DELIMITER ;
CALL FixOrdersColumns();
DROP PROCEDURE IF EXISTS FixOrdersColumns;

UPDATE customers SET full_name = 'Nguyễn Văn Khánh Hàng', address = '789 Đường 3/2, Quận 10, TP. HCM' WHERE user_id = 2;
UPDATE users SET full_name = 'Nguyễn Văn Khánh Hàng' WHERE username = 'user';
